name: Alerta CI - Hola Mundo

on:
  push:
    branches:
      - main

jobs:
  notificacion:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repositorio
        uses: actions/checkout@v4

      # Paso 2: Ejecutar Hola Mundo
      - name: Ejecutar programa
        run: |
          node index.js

      # Paso 3: Enviar notificaciÃ³n a ntfy
      - name: Enviar alerta a ntfy
        run: |
          curl -X POST https://ntfy.sh/devops-itla \
          -H "Title: ðŸš€ Deploy en main" \
          -H "Priority: high" \
          -d "Se subiÃ³ cÃ³digo al branch main correctamente."
